### ISSUE TITLE
Définir format fichiers configuration

### ISSUE THREAD

**Issue by AnthoJack** [gen-classroom/projet-godi_issolah_jaccard_thullen#22]
En tant qu’utilisateur, j’aimerais que toutes les données structurées du site (p.ex. configuration, métadonnées, etc.) puissent être saisies dans un format uniforme tel que JSON, YAML ou TOML

**Comment by ubervison** [comment]
Les données structurées du site seront saisies dans le format YAML.

**Comment by ubervison** [comment]
Le fichier de configuration généralisé `config.yaml` contiendra les métadonnées suivantes : 

- `titre` : le titre du site
- `domaine` : le domaine sur lequel le site est hébergé
- `description` une description générale pour le site
