### ISSUE TITLE
Definir structure fichiers contenu

### ISSUE THREAD

**Issue by AnthoJack** [gen-classroom/projet-godi_issolah_jaccard_thullen#26]
En tant qu’utilisateur, j’aimerai pouvoir créer des pages contenant des métadonnées et du contenu. Par exemple, le format suivant répondrait à ce besoin:
```
titre: Mon premier article
auteur: Bertil Chapuis
date: 2021-03-10
---
# Mon premier article
## Mon sous-titre
Le contenu de mon article.
![Une image](./image.png)
```

**Comment by ubervison** [comment]
Les métadonnées avant le séparateur `---` sont saisies au format YAML. 

Les métadonnées disponibles sont : 

`titre` : le titre de la page
`auteur` : l'auteur de la page
`date` : la de publication de la page
`tags` : une liste de tags associés à cette page

Le contenu est saisi au format markdown.
