### ISSUE TITLE
Automatisation des releases

### ISSUE THREAD

**Issue by AnthoJack** [gen-classroom/projet-godi_issolah_jaccard_thullen#47]
En tant que développeur, j’aimerai que la création et la publication d’une nouvelle release soit automatisée à l’aide de GitHub actions. En d’autres termes, j’aimerai que le fichier jar ou le fichier zip de la release soit publié de manière automatique lorsqu’un tag correspondant à une version (p.ex. v0.0.2) est publié sur git

**Comment by issolahma** [comment]
Done
