### ISSUE TITLE
Moteur de template

### ISSUE THREAD

**Issue by AnthoJack** [gen-classroom/projet-godi_issolah_jaccard_thullen#49]
En tant qu’utilisateur, j’aimerai pouvoir utiliser un moteur de template (p.ex.Handlebars1) de manière à enrichir mes pages HTML avec des éléments d’interfaces (header, footer, menu, etc.). En d’autres termes, j’aimerai que le HTML correspondant à mes fichiers Markdown soit injecté dans des pages HTML plus complètes à l’aide d’un template.

**Comment by AnthoJack** [comment]
Le moteur de template doit s'exécuter lors de l'appel à build mais doit s'exécuter avant les opérations de compilation MD et YAML

**Comment by ubervison** [comment]
Un template consiste en un fichier nommé layout.html. Le document html correspondant est produit grâce à deux types de substitution : 

- Subsitution d'une chaîne de caractère, dans une balise `{{ string }}`
- Inclusion d'un document externe dans une balise `{% include.html }`
