### ISSUE TITLE
Génération à la volée

### ISSUE THREAD

**Issue by AnthoJack** [gen-classroom/projet-godi_issolah_jaccard_thullen#59]
En tant qu’utilisateur, j’aimerai que les commandes build et serve puissent régénérer le site statique à la volée, c’est-à-dire de manière automatique lorsque des changements sont effectués sur le système de fichier. Pour cela, ajoutez une option --watch aux commandes build et serve et assurez-vous que leur exécution ne se termine pas à la fin du premier build

**Comment by ubervison** [comment]
Si une **ressource** (image par exemple) est modifiée, il faut seulement la copier dans le site final.

Si le **contenu** d'un article est modifié, il faut seulement recompiler l'article.

Dans tous les autres cas (configuration YAML du site, template, menu), l'intégralité du site doit être recompilé.

**Comment by ubervison** [comment]
Refactoring à faire :

- Dans `SubCommandBuild` :
    - Découpler/refactoriser les fonctions qui servent à compiler/copier dans le site dans une nouvelle classe `SiteBuilder`, de manière à pouvoir les appeler de manière statique.
