### ISSUE TITLE
Code Coverage

### ISSUE THREAD

**Issue by AnthoJack** [gen-classroom/projet-godi_issolah_jaccard_thullen#62]
Configurez Jacoco ou un outil équivalent pour calculer le degré de couverture de votre code par des tests unitaires et d’intégration. Ajoutez les données de couverture à votre rapport

**Comment by issolahma** [comment]
https://www.jetbrains.com/help/idea/code-coverage.html

**Comment by issolahma** [comment]
Done (pas de PR)
